import { validate as validate1 } from "./validator1";
import { validate as validate2 } from "./validator2";
import { validate as validate3 } from "./validator3";
import { validate as validate4 } from "./validator4";
import { validate as validate5 } from "./validator5";
import { validate as validate6 } from "./validator6";
import { validate as validate7 } from "./validator7";
import { validate as validate8 } from "./validator8";
import { validate as validate9 } from "./validator9";
import { validate as validate10 } from "./validator10";
import { validate as validate11 } from "./validator11";
import { validate as validate13 } from "./validator13";
import { validate as validate14 } from "./validator14";
import { validate as validate15 } from "./validator15";
import { validate as validate16 } from "./validator16";
import { validate as validate17 } from "./validator17";
import { validate as validate18 } from "./validator18";
import { validate as validate19 } from "./validator19";
import { validate as validate20 } from "./validator20";
import { validate as validate21 } from "./validator21";
import { validate as validate22 } from "./validator22";
import { validate as validate23 } from "./validator23";
import { validate as validate24 } from "./validator24";
import { validate as validate25 } from "./validator25";
import { validate as validate26 } from "./validator26";
import { validate as validate27 } from "./validator27";
import { validate as validate28 } from "./validator28";
import { validate as validate29 } from "./validator29";
import { validate as validate30 } from "./validator30";
import { validate as validate31 } from "./validator31";
import { validate as validate32 } from "./validator32";
import { validate as validate34 } from "./validator34";
import { validate as validate35 } from "./validator35";
import { validate as validate36 } from "./validator36";
import { validate as validate37 } from "./validator37";
import { validate as validate38 } from "./validator38";
import { validate as validate39 } from "./validator39";
import { validate as validate40 } from "./validator40";
import { validate as validate41 } from "./validator41";
import { validate as validate42 } from "./validator42";

export async function validate(text) {
  let result = validate1(text);
  result = validate2(result);
  result = validate3(result);
  result = validate4(result);
  result = validate5(result);
  result = validate6(result);
  result = validate7(result);
  result = validate8(result);
  result = validate9(result);
  result = validate10(result);
  result = validate11(result);
  result = validate13(result);
  result = validate14(result);
  result = validate15(result);
  result = validate16(result);
  result = validate17(result);
  result = validate18(result);
  result = validate19(result);
  result = validate20(result);
  result = validate21(result);
  result = validate22(result);
  result = validate23(result);
  result = validate24(result);
  result = validate25(result);
  result = validate26(result);
  result = validate27(result);
  result = validate28(result);
  result = validate29(result);
  result = validate31(result);
  result = validate30(result);
  result = validate32(result);
  result = validate34(result);
  result = validate35(result);
  result = validate36(result);
  result = validate37(result);
  result = validate38(result);
  result = validate39(result);
  result = validate40(result);
  result = validate41(result);
  result = validate42(result);
  return result;
}
